name:                GroupCoursework
version:             0.1.0.0
github:              "shristi0002/GroupCoursework"
license:             BSD3
author:              "Shristi"
maintainer:          "shristi0002@gmail.com"
copyright:           "Shisti Sharma, Divya Chaudhary, Prem Chand Vangapandu, Harman Preet Singh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Coursework

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/shristi0002/GroupCoursework#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  GroupCoursework-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GroupCoursework

tests:
  GroupCoursework-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GroupCoursework
